//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WallsWS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class AGENDA
    {
        public int agen_id { get; set; }
        public int barb_id { get; set; }
        public int serv_id { get; set; }
        public int hrdi_id { get; set; }
        public string cust_name { get; set; }
        public string cust_phone { get; set; }
        public string cust_mail { get; set; }
        public string agen_date { get; set; }
        public Nullable<int> agen_status { get; set; }
    }
}
