

//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------


namespace WallsWS.Models
{

using System;
using System.Data.Entity;
using System.Data.Entity.Infrastructure;

using System.Data.Entity.Core.Objects;
using System.Linq;


public partial class AppDTEntities : DbContext
{
    public AppDTEntities()
        : base("name=AppDTEntities")
    {

    }

    protected override void OnModelCreating(DbModelBuilder modelBuilder)
    {
        throw new UnintentionalCodeFirstException();
    }


    public virtual DbSet<HORARIO_DISPONIBLE> HORARIO_DISPONIBLE { get; set; }

    public virtual DbSet<SUCURSAL> SUCURSAL { get; set; }

    public virtual DbSet<BARBEROS> BARBEROS { get; set; }

    public virtual DbSet<USUARIOS> USUARIOS { get; set; }

    public virtual DbSet<HORARIO> HORARIO { get; set; }

    public virtual DbSet<TICKETS> TICKETS { get; set; }

    public virtual DbSet<BARBERO_PAGO> BARBERO_PAGO { get; set; }

    public virtual DbSet<AGENDA> AGENDA { get; set; }

    public virtual DbSet<vis_Set_Agenda> vis_Set_Agenda { get; set; }

    public virtual DbSet<PRODUCTOS> PRODUCTOS { get; set; }

    public virtual DbSet<SERVICIOS> SERVICIOS { get; set; }

    public virtual DbSet<vis_AGENDA> vis_AGENDA { get; set; }

    public virtual DbSet<vis_AGENDA_BARBEROS> vis_AGENDA_BARBEROS { get; set; }

    public virtual DbSet<VENTASTICKET> VENTASTICKET { get; set; }

    public virtual DbSet<BARBERO_COMISION> BARBERO_COMISION { get; set; }

    public virtual DbSet<vis_VENTASTICKET_PRODUCTOS> vis_VENTASTICKET_PRODUCTOS { get; set; }


    public virtual int sp_SET_HORARIO(Nullable<int> barbid)
    {

        var barbidParameter = barbid.HasValue ?
            new ObjectParameter("barbid", barbid) :
            new ObjectParameter("barbid", typeof(int));


        return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_SET_HORARIO", barbidParameter);
    }


    public virtual ObjectResult<sp_Barberos_Pagos_Result> sp_Barberos_Pagos(Nullable<int> barber)
    {

        var barberParameter = barber.HasValue ?
            new ObjectParameter("barber", barber) :
            new ObjectParameter("barber", typeof(int));


        return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_Barberos_Pagos_Result>("sp_Barberos_Pagos", barberParameter);
    }

}

}

