
//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------


namespace WallsWS.Models
{

using System;
    using System.Collections.Generic;
    
public partial class BARBEROS
{

    public int barb_id { get; set; }

    public int sucu_id { get; set; }

    public string barb_name { get; set; }

    public string barb_phone { get; set; }

    public string barb_mail { get; set; }

    public string barb_user { get; set; }

    public string barb_password { get; set; }

    public string barb_urlimage { get; set; }

}

}
