//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WallsWS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class BARBERO_PAGO
    {
        public int pago_Id { get; set; }
        public int sucu_Id { get; set; }
        public int barb_Id { get; set; }
        public double pago_total { get; set; }
        public double pago_procent { get; set; }
        public System.DateTime pago_date { get; set; }
    }
}
