//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WallsWS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class BARBERO_COMISION
    {
        public int comi_Id { get; set; }
        public int sucu_Id { get; set; }
        public int barb_Id { get; set; }
        public double serv_id { get; set; }
        public double como_procent { get; set; }
    }
}
