
//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------


namespace WallsWS.Models
{

using System;
    using System.Collections.Generic;
    
public partial class BARBERO_PAGO
{

    public int pago_Id { get; set; }

    public int sucu_Id { get; set; }

    public int barb_Id { get; set; }

    public double pago_total { get; set; }

    public double pago_procent { get; set; }

    public System.DateTime pago_date { get; set; }

}

}
