
//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------


namespace WallsWS.Models
{

using System;
    using System.Collections.Generic;
    
public partial class HORARIO_DISPONIBLE
{

    public int hrdi_id { get; set; }

    public Nullable<int> barb_id { get; set; }

    public string hrdi_hora { get; set; }

    public string hrdi_date { get; set; }

    public Nullable<int> hrdi_status { get; set; }

}

}
