//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WallsWS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class HORARIO_DISPONIBLE
    {
        public int hrdi_id { get; set; }
        public Nullable<int> barb_id { get; set; }
        public string hrdi_hora { get; set; }
        public string hrdi_date { get; set; }
        public Nullable<int> hrdi_status { get; set; }
    }
}
