//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WallsWS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class HORARIO
    {
        public int hora_id { get; set; }
        public int sucu_id { get; set; }
        public string hora_desc { get; set; }
        public string hora_date { get; set; }
        public Nullable<int> hora_status { get; set; }
    }
}
