
//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------


namespace WallsWS.Models
{

using System;
    using System.Collections.Generic;
    
public partial class HORARIO
{

    public int hora_id { get; set; }

    public int sucu_id { get; set; }

    public string hora_desc { get; set; }

    public string hora_date { get; set; }

    public Nullable<int> hora_status { get; set; }

}

}
