
//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------


namespace WallsWS.Models
{

using System;
    using System.Collections.Generic;
    
public partial class PRODUCTOS
{

    public int prod_id { get; set; }

    public int sucu_id { get; set; }

    public string prod_sku { get; set; }

    public string prod_name { get; set; }

    public string prod_desc { get; set; }

    public Nullable<double> prod_price { get; set; }

    public Nullable<int> prod_stock { get; set; }

}

}
