//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WallsWS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PRODUCTOS
    {
        public int prod_id { get; set; }
        public int sucu_id { get; set; }
        public string prod_sku { get; set; }
        public string prod_name { get; set; }
        public string prod_desc { get; set; }
        public Nullable<double> prod_price { get; set; }
        public Nullable<int> prod_stock { get; set; }
    }
}
