//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WallsWS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SERVICIOS
    {
        public int serv_id { get; set; }
        public int sucu_id { get; set; }
        public string serv_sku { get; set; }
        public string serv_name { get; set; }
        public string serv_desc { get; set; }
        public Nullable<double> serv_price { get; set; }
    }
}
