
//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------


namespace WallsWS.Models
{

using System;
    using System.Collections.Generic;
    
public partial class SERVICIOS
{

    public int serv_id { get; set; }

    public int sucu_id { get; set; }

    public string serv_sku { get; set; }

    public string serv_name { get; set; }

    public string serv_desc { get; set; }

    public Nullable<double> serv_price { get; set; }

    public Nullable<double> serv_comi { get; set; }

}

}
