
//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------


namespace WallsWS.Models
{

using System;
    using System.Collections.Generic;
    
public partial class SUCURSAL
{

    public int sucu_id { get; set; }

    public string sucu_name { get; set; }

    public string sucu_addres { get; set; }

    public string sucu_lat { get; set; }

    public string sucu_lon { get; set; }

    public string sucu_phone { get; set; }

}

}
