//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WallsWS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SUCURSAL
    {
        public int sucu_id { get; set; }
        public string sucu_name { get; set; }
        public string sucu_addres { get; set; }
        public string sucu_lat { get; set; }
        public string sucu_lon { get; set; }
        public string sucu_phone { get; set; }
    }
}
