//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WallsWS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class VENTASTICKET
    {
        public int Venta_Id { get; set; }
        public int Ticket_Id { get; set; }
        public int Prod_Id { get; set; }
        public int Venta_Cantidad { get; set; }
        public double Prod_Price { get; set; }
        public double Venta_Importe { get; set; }
        public Nullable<double> venta_discount { get; set; }
        public string disc_desc { get; set; }
    }
}
