
//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------


namespace WallsWS.Models
{

using System;
    using System.Collections.Generic;
    
public partial class vis_Ticket_Detail
{

    public int venta_id { get; set; }

    public int ticket_id { get; set; }

    public int prod_id { get; set; }

    public string serv_name { get; set; }

    public int venta_cantidad { get; set; }

    public double prod_price { get; set; }

    public double Venta_Importe { get; set; }

    public Nullable<double> venta_discount { get; set; }

    public string disc_desc { get; set; }

    public Nullable<double> serv_comi { get; set; }

}

}
