//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WallsWS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class vis_GUIAS
    {
        public int guia_id { get; set; }
        public Nullable<int> guia_origen { get; set; }
        public string origen { get; set; }
        public Nullable<int> guia_destino { get; set; }
        public string destino { get; set; }
        public string guia_code { get; set; }
        public System.DateTime guia_date { get; set; }
        public int tran_id { get; set; }
        public string tran_name { get; set; }
        public Nullable<int> guia_status { get; set; }
    }
}
