
//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------


namespace WallsWS.Models
{

using System;
    using System.Collections.Generic;
    
public partial class vis_Get_Quanty_Product
{

    public int sucu_id { get; set; }

    public int Prod_Id { get; set; }

    public string serv_name { get; set; }

    public Nullable<int> productos { get; set; }

}

}
