
//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------


namespace WallsWS.Models
{

using System;
    using System.Collections.Generic;
    
public partial class vis_AGENDA
{

    public int agen_id { get; set; }

    public int barb_id { get; set; }

    public int sucu_id { get; set; }

    public string barb_name { get; set; }

    public int serv_id { get; set; }

    public string serv_name { get; set; }

    public string cust_name { get; set; }

    public string cust_phone { get; set; }

    public string cust_mail { get; set; }

    public string agen_date { get; set; }

    public string hrdi_hora { get; set; }

    public Nullable<double> serv_price { get; set; }

    public Nullable<int> agen_status { get; set; }

}

}
