
//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------


namespace WallsWS.Models
{

using System;
    using System.Collections.Generic;
    
public partial class vis_VENTASTICKET_PRODUCTOS
{

    public int Venta_Id { get; set; }

    public int Ticket_Id { get; set; }

    public int Prod_Id { get; set; }

    public string serv_name { get; set; }

    public int Venta_Cantidad { get; set; }

    public double Prod_Price { get; set; }

    public double Venta_Importe { get; set; }

    public Nullable<double> venta_discount { get; set; }

    public string disc_desc { get; set; }

}

}
